export enum CommonState {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED'
}

export enum SexState {
  FAMALE = 'FAMALE',
  MALE = 'MALE'
}

export enum DictType {
  CommonState = 'CommonState',
  SexState = 'SexState',
  MessageType = 'MessageType',
  FocusType = 'FocusType'
}

export enum MessageType {
  RISK = 'RISK',
  MARKETING = 'MARKETING',
  CUSTOMER = 'CUSTOMER',
  WORK = 'WORK'
}

export enum MessageTagType {
  CUSTOMERPOTENTIAL = 'CUSTOMER-POTENTIAL',
  LOANAPPLICATION = 'LOAN-APPLICATION',
  LOADAPPROVAL = 'LOAD-APPROVAL',
  LOANOVERDUE = 'LOAN-OVERDUE',
  RISKLOSS = 'RISK-LOSS',
  RISKDOWNGRADE = 'RISK-DOWNGRADE',
  MARKETINGACTIVITY = 'MARKETING-ACTIVITY',
  CUSTOMERRECOMMEND = 'CUSTOMER-RECOMMEND',
  CUSTOMERSIGNING = 'CUSTOMER-SIGNING',
  WORKPERFORMANCE = 'WORK-PERFORMANCE',
  WORKVISIT = 'WORK-VISIT',
  WORKTELEPHONE = 'WORK-TELEPHONE'
}

export enum ProductType {
  SHANGHUDAI = 'SHANGHUDAI',
  QIYEDAI = 'QIYEDAI'
}

export enum FocusType {
  ACTIVE = 'FOCUS-ACTIVE',
  CUSTOMER = 'FOCUS-CUSTOMER',
  PRODUCT = 'FOCUS-PRODUCT',
  CHANNEL = 'FOCUS-CHANNEL',
  INCIDENT = 'FOCUS-INCIDENT'
}
